from users.serializers.roles.company import CompanySerializer, CompanyMinimumSerializer
from users.serializers.roles.student import StudentSerializer, StudentMinimumSerializer, StudentMinInfoSerializer
