# Generated by Django 2.1.7 on 2019-10-06 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_domain', models.CharField(blank=True, max_length=55, verbose_name='Company Domain')),
                ('category_of_company', models.CharField(blank=True, max_length=50, verbose_name='Category of Company')),
                ('team_size', models.CharField(blank=True, max_length=100, verbose_name='Team size')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
            ],
            options={
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(db_index=True, help_text='If you are company,enter Company name.', max_length=50, unique=True, verbose_name='Username/Company Name')),
                ('email', models.CharField(db_index=True, help_text='If you are company,enter Company email.', max_length=50, unique=True, verbose_name='Email/Company email')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('secondary_email', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Secondary Email')),
                ('is_company', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('starred_posts', models.ManyToManyField(blank=True, related_name='starred_post_set', to='post.Post')),
            ],
            options={
                'verbose_name_plural': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=55, verbose_name='Branch')),
                ('enrollment_number', models.CharField(blank=True, max_length=20, verbose_name='Enrollment number')),
                ('course', models.CharField(blank=True, max_length=55, verbose_name='Course')),
                ('year', models.CharField(blank=True, max_length=55, verbose_name='Year')),
                ('social_links', models.TextField(blank=True, verbose_name='Social links')),
                ('skills', models.TextField(blank=True, verbose_name='Skills')),
                ('interest', models.TextField(blank=True, verbose_name='Interest')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('achievements', models.TextField(blank=True, verbose_name='Achievements')),
                ('profile_image', models.ImageField(default='null', help_text='If you are company,enter company icon.', upload_to='profile_image/')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='users.Person')),
            ],
            options={
                'verbose_name_plural': 'Student',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='users.Person'),
        ),
    ]
