# Generated by Django 2.2.10 on 2020-02-26 11:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models.social_link


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(db_index=True, help_text='If you are company,enter Company name.', max_length=50, unique=True, verbose_name='Username/Company Name')),
                ('email', models.CharField(db_index=True, help_text='If you are company,enter Company email.', max_length=50, unique=True, verbose_name='Email/Company email')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('secondary_email', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Secondary Email')),
                ('profile_image', models.ImageField(default='null', help_text='If you are company,enter company icon.', upload_to='profile_image/')),
                ('is_company', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'User',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_logo', models.ImageField(default='null', upload_to='social_link_logo/', validators=[users.models.social_link.SocialLink.validate_image])),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utilities.Website')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone Number Not Valid', regex='^[6-9]\\d{9}$')])),
                ('enrollment_number', models.CharField(blank=True, max_length=20, verbose_name='Enrollment number')),
                ('course', models.CharField(blank=True, max_length=55, verbose_name='Course')),
                ('year', models.CharField(blank=True, max_length=55, verbose_name='Year')),
                ('interest', models.TextField(blank=True, verbose_name='Interest')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('achievements', models.TextField(blank=True, verbose_name='Achievements')),
                ('branch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_branch', to='utilities.Branch')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='student_skill', to='utilities.Skill')),
                ('social_links', models.ManyToManyField(related_name='social_links', to='users.SocialLink')),
            ],
            options={
                'verbose_name_plural': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_domain', models.CharField(blank=True, max_length=55, verbose_name='Company Domain')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone Number Not Valid', regex='^[6-9]\\d{9}$')])),
                ('category_of_company', models.CharField(blank=True, max_length=50, verbose_name='Category of Company')),
                ('team_size', models.CharField(blank=True, max_length=100, verbose_name='Team size')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company',
            },
        ),
    ]
