# Generated by Django 2.2.10 on 2020-02-25 15:20

from django.db import migrations, models
import django.db.models.deletion
import users.models.social_link


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_websitemodel'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_logo', models.ImageField(default='null', upload_to='social_link_logo/', validators=[users.models.social_link.SocialLink.validate_image])),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utilities.WebsiteModel')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='social_links',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.SocialLink'),
        ),
    ]
