# Generated by Django 2.1.7 on 2019-10-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_auto_20191009_0147'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ManyToManyField(blank=True, related_name='student_branch', to='utilities.Branch'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='skills',
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='student_skill', to='utilities.Skill'),
        ),
    ]
