# Generated by Django 2.1.7 on 2019-05-17 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Company', 'Company'), ('Student', 'Student')], default='Student', max_length=20, verbose_name='User type')),
                ('branch', models.CharField(blank=True, max_length=55, verbose_name='Branch')),
                ('enrollment_number', models.CharField(blank=True, max_length=20, verbose_name='Enrollment number')),
                ('year', models.CharField(blank=True, max_length=55, verbose_name='Year')),
                ('social_links', models.TextField(blank=True, verbose_name='Social links')),
                ('skills', models.TextField(blank=True, verbose_name='Skills')),
                ('interest', models.TextField(blank=True, verbose_name='Interest')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('achievements', models.TextField(blank=True, verbose_name='Achievements')),
                ('profile_image', models.URLField(blank=True, verbose_name='Profile image')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
            ],
            options={
                'verbose_name_plural': 'User profile',
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
