# Generated by Django 2.1.7 on 2019-10-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191006_1149'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'User'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='starred_posts',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='person',
            name='profile_image',
            field=models.ImageField(default='null', help_text='If you are company,enter company icon.', upload_to='profile_image/'),
        ),
        migrations.AddField(
            model_name='student',
            name='starred_posts',
            field=models.ManyToManyField(blank=True, related_name='starred_post_set', to='post.Post'),
        ),
    ]
