# Generated by Django 2.2.10 on 2020-02-25 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200225_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='social_links',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='users.SocialLink'),
        ),
    ]
