# Generated by Django 2.1.7 on 2019-10-07 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191006_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
