# Generated by Django 2.1.7 on 2020-03-28 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sociallink_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='profile_url',
            field=models.URLField(default='www.tusharvarshney.com', validators=[django.core.validators.URLValidator]),
            preserve_default=False,
        ),
    ]
