# Generated by Django 2.1.7 on 2019-10-09 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_auto_20191009_0147'),
        ('users', '0002_auto_20191009_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_branch', to='utilities.Branch'),
        ),
    ]
