# Generated by Django 2.2.10 on 2020-02-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200225_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='social_links',
        ),
        migrations.AddField(
            model_name='student',
            name='social_links',
            field=models.ManyToManyField(related_name='social_links', to='users.SocialLink'),
        ),
    ]
