# Generated by Django 2.1.7 on 2020-04-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200404_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(db_index=True, help_text='If you are company,enter Company email.', max_length=50, unique=True, verbose_name='Email/Company email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='secondary_email',
            field=models.EmailField(blank=True, db_index=True, max_length=50, verbose_name='Secondary Email'),
        ),
    ]
