# Generated by Django 2.1.7 on 2020-04-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200426_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='If you are company,enter company icon.', null=True, upload_to='profile_image/'),
        ),
    ]
