# Generated by Django 2.1.7 on 2020-04-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200427_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='availability_status',
            field=models.BooleanField(default=True),
        ),
    ]
