# Generated by Django 2.1.7 on 2020-04-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_followuser"),
        ("users", "0012_student_availability_status"),
    ]

    operations = []
