# Generated by Django 2.1.7 on 2020-05-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_auto_20200430_2319"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sociallink",
            options={"verbose_name_plural": "Social Links"},
        ),
    ]
