# Generated by Django 2.1.7 on 2020-06-21 10:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_auto_20200616_1956"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="achievements",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
    ]
