# Generated by Django 2.1.7 on 2020-06-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200621_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_channeli_oauth',
            field=models.BooleanField(default=False),
        ),
    ]
