# Generated by Django 2.1.7 on 2020-06-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_person_is_channeli_oauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
