# Generated by Django 3.2.6 on 2021-09-11 12:40

import common.get_file_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_image',
            field=models.ImageField(blank=True, default='defaults/profile-image.png', help_text='If you are company,enter company icon.', null=True, upload_to=common.get_file_path.get_profile_image_path),
        ),
    ]
