# Generated by Django 3.2.6 on 2022-10-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_person_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, db_index=True, help_text='If you are company,enter Company email.', max_length=50, null=True, verbose_name='Email/Company email'),
        ),
    ]
