language: python
python:
- "3.8"
# setup environment
env:
- DJANGO_VERSION=2.1.7
# install dependencies
install:
- pip install -r requirements.txt

#Nortifiactions
notifications:  
  email:  
    recipients:  
    - srivastavayash58@gmail.com
    on_success: always  
    on_failure: always

# run test scripts
script:
- python manage.py test 