# Generated by Django 2.1.7 on 2019-10-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmark_competition', to='users.Student'),
        ),
        migrations.AddField(
            model_name='project',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmark_project', to='users.Student'),
        ),
    ]
