# Generated by Django 2.1.7 on 2020-03-31 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmark_project', to='users.Student'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internship',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmark_internship', to='users.Student'),
        ),
        migrations.AddField(
            model_name='internship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competition',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmark_competition', to='users.Student'),
        ),
        migrations.AddField(
            model_name='competition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
