# Generated by Django 2.1.7 on 2020-04-16 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200415_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={},
        ),
        migrations.AlterModelOptions(
            name='internship',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
