# Generated by Django 2.1.7 on 2020-04-18 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("post", "0012_auto_20200418_2303"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppliedPostEntries",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_object_id", models.PositiveIntegerField()),
                ("post_object_id", models.PositiveIntegerField()),
                (
                    "post_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applied_post_entries_post",
                        to="contenttypes.ContentType",
                    ),
                ),
                (
                    "user_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applied_user_entries_post",
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Applied Post Entries",
            },
        ),
    ]
