# Generated by Django 2.1.7 on 2020-06-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0027_auto_20200603_1408"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internship",
            name="work_type",
        ),
    ]
