# Generated by Django 2.1.7 on 2020-06-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0028_remove_internship_work_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="duration_unit",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Day"), (2, "Week"), (3, "Month"), (4, "Year")],
                default=3,
            ),
        ),
        migrations.AlterField(
            model_name="internship",
            name="duration_value",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Duration"
            ),
        ),
    ]
