# Generated by Django 3.2.6 on 2022-10-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0036_auto_20211014_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='google_form_link',
            field=models.URLField(blank=True, default=None, max_length=55, null=True, verbose_name='Google Form Link'),
        ),
    ]
