from post.serializers.post_roles.project import ProjectSerializer
from post.serializers.post_roles.internship import InternshipSerializer
from post.serializers.post_roles.competition import CompetitionSerializer
