# Generated by Django 2.1.7 on 2020-04-15 14:32

from django.db import migrations, models
import utilities.models.website


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="website_logo",
            field=models.ImageField(
                blank=True,
                default="null",
                upload_to="social_link_logo/",
                validators=[utilities.models.website.validate_image],
            ),
        ),
    ]
