# Generated by Django 2.1.7 on 2019-10-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='Type the skill name you want to add', max_length=255, verbose_name='Skill'),
        ),
    ]
