# Generated by Django 2.2.10 on 2020-02-25 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website_name', models.CharField(max_length=155, verbose_name='Website')),
                ('website_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator])),
            ],
            options={
                'verbose_name_plural': 'websites',
            },
        ),
    ]
