# Generated by Django 2.1.7 on 2019-10-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_auto_20191009_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Type the Location name to be added..', max_length=255, verbose_name='Location')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='State')),
                ('country', models.CharField(default='India', max_length=255, verbose_name=255)),
                ('pin_code', models.IntegerField(unique=True, verbose_name='Pincode')),
            ],
            options={
                'verbose_name_plural': 'Location',
            },
        ),
    ]
