# Generated by Django 2.1.7 on 2020-02-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(default='India', max_length=255, verbose_name='Country'),
        ),
    ]
