# Generated by Django 2.1.7 on 2020-05-11 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0006_auto_20200430_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
    ]
