# Generated by Django 2.1.7 on 2020-05-11 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0007_remove_state_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="country",
                to="utilities.Country",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="state",
                to="utilities.State",
            ),
        ),
    ]
