# Generated by Django 2.1.7 on 2020-06-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0009_location_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="slug",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
