# Generated by Django 3.2.5 on 2021-10-31 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0010_auto_20200603_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('type', models.CharField(blank=True, default=None, help_text='Type of skill you want to add', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Type',
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.skilltype'),
        ),
    ]
