# Generated by Django 3.2.5 on 2021-10-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0010_auto_20200603_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name_plural': 'Type'},
        ),
    ]
