# Generated by Django 3.2.5 on 2021-10-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0011_alter_skill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name_plural': 'Skill'},
        ),
    ]
