# Generated by Django 3.2.5 on 2021-10-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0012_alter_skill_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='Type',
            field=models.CharField(default='tech', max_length=255),
        ),
    ]
