# Generated by Django 3.2.5 on 2021-10-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0013_skill_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='Type',
        ),
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.CharField(default='tech', help_text='Type of skill you want to add', max_length=255),
        ),
    ]
