# Generated by Django 3.2.5 on 2021-10-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0014_auto_20211030_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='type',
        ),
        migrations.AddField(
            model_name='skill',
            name='Type',
            field=models.CharField(default='tech', help_text='Type of skill you want to add', max_length=255),
        ),
    ]
