# Generated by Django 3.2.5 on 2021-10-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0015_auto_20211030_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='Type',
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('type', models.CharField(default='tech', help_text='Type of skill you want to add', max_length=255)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.skill')),
            ],
            options={
                'verbose_name_plural': 'Type',
            },
        ),
    ]
