# Generated by Django 3.2.5 on 2021-10-30 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0016_auto_20211030_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utilities.skill'),
        ),
    ]
